
#include "config.h"

#include <map>
#include <string>

void help(const char* prog)
{
    printf("syntax:\n");
    printf("\t%s copy    <service> [object]          ", prog);
    printf("-> copy data from existent service, prints in stdout\n");
    printf("\t%s service <copied-service-data-file> ", prog);
    printf(" -> create service with data\n");
}

/******* external functions ******/

// clone a service data from a openbmc system (usually a real machine)
//   generates a text file
int clone_service(int argc, char *argv[]);

// creates the service and data with information from a file
//   generated by clone_service()
int emulate_service(char *filename);


int main(int argc, char *argv[])
{
    int ret = 0;
    if (argc < 3)
    {
        help(argv[0]);
    }
    else
    {
        std::string action{argv[1]};
        if (action == "copy")
        {
            ret = clone_service(argc, argv);
        }
        else if (action == "service")
        {
            ret = emulate_service(argv[2]);
        }
        else
        {
            help(argv[0]);
        }
    }
    return ret;
}
